annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.17-fba90f129f04ad57b26d0f5a9b25da11d2703aee.tgz
dateCreated: '2025-12-09T16:12:57.683247Z'
digest: 8a6583391ae84e7509530e96bfd975a5665e37983af1270d2b9780c8b6637c67
home: https://github.com/giantswarm/mcp-prometheus
icon: https://github.com/prometheus/prometheus/raw/main/documentation/images/prometheus-logo.svg
