annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-abbeb636db7a1f49cf3c38dbcdf9fa45619196a7.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-abbeb636db7a1f49cf3c38dbcdf9fa45619196a7.tgz-meta/README.md
  application.giantswarm.io/team: planeteers
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-abbeb636db7a1f49cf3c38dbcdf9fa45619196a7.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.17-abbeb636db7a1f49cf3c38dbcdf9fa45619196a7.tgz
dateCreated: '2025-11-23T17:02:54.862639Z'
digest: c6ca5eb95b7f2d20b03ad4d9a5665ba51871c786cceff4f4949220bca829d324
home: https://github.com/giantswarm/mcp-prometheus
icon: https://github.com/prometheus/prometheus/raw/main/documentation/images/prometheus-logo.svg
