annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-a86d04718c7174025deece8ec8104bf9be8c8bd1.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-a86d04718c7174025deece8ec8104bf9be8c8bd1.tgz-meta/README.md
  application.giantswarm.io/team: planeteers
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-a86d04718c7174025deece8ec8104bf9be8c8bd1.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.17-a86d04718c7174025deece8ec8104bf9be8c8bd1.tgz
dateCreated: '2025-12-29T04:47:55.010153Z'
digest: cffde2db7372d4ccedcf7625c27482ef797cfcd5554f559c425528eae5bec195
home: https://github.com/giantswarm/mcp-prometheus
icon: https://github.com/prometheus/prometheus/raw/main/documentation/images/prometheus-logo.svg
