annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-55cb4ea17c84ecb30beaa2d7ea2d1414ce2ccfab.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-55cb4ea17c84ecb30beaa2d7ea2d1414ce2ccfab.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-55cb4ea17c84ecb30beaa2d7ea2d1414ce2ccfab.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-55cb4ea17c84ecb30beaa2d7ea2d1414ce2ccfab.tgz
dateCreated: '2025-12-01T20:40:27.831320Z'
digest: da648ce75dfa28f60672300d9d83772c76c22f16293d811e7e9efce85d73c4ff
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
