annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-18.0.0-b293b98f2e07fd40c43fcacccf19621828d9c9c5.tgz
dateCreated: '2025-12-10T17:58:03.778114Z'
digest: e19a8408aa706b443c9c2cefbf1f9d2348ef6f00aa75f9e02b51414d4ae4327e
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
