annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/prometheus-operator-crd-18.0.0-54690d96f9852ac48760b953ccb8877788c09a21.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/prometheus-operator-crd-18.0.0-54690d96f9852ac48760b953ccb8877788c09a21.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/prometheus-operator-crd-18.0.0-54690d96f9852ac48760b953ccb8877788c09a21.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-operator-crd-18.0.0-54690d96f9852ac48760b953ccb8877788c09a21.tgz
dateCreated: '2025-12-02T12:55:46.947667Z'
digest: ac3e30d3292e18df0ce61a1e60fc0341445f88cc0f069ef1702f78c5f05c7f5a
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
