annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.0-e09425d741e9c28055a58b8f0f4ece2911ce39ec.tgz
dateCreated: '2025-12-29T13:23:53.492969Z'
digest: 105627320a5e2e60bc8e618e68e392adbd84e134ae7aa718ecdfc67147e4aed3
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
