annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.1-6695bcaca7a82d572c1de298690dda0162beb2f9.tgz
dateCreated: '2026-01-23T23:36:17.811210Z'
digest: 8ba1614138fec28edfb43c1163d95d494d38595e3165a7749651f00eab18c6b0
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
