annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.0-cd11513174eb20314e31940fad3960ea629c258b.tgz
dateCreated: '2025-12-17T18:13:25.783213Z'
digest: 62061b0f43b7658d330818e7140781c8530a77e1d050789c36b6cba195b90dce
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
