annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/alertmanager-to-github-0.2.0-ee8a681cb08d0becda79f9725784e33a2ebf36a1.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/alertmanager-to-github-0.2.0-ee8a681cb08d0becda79f9725784e33a2ebf36a1.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/alertmanager-to-github-0.2.0-ee8a681cb08d0becda79f9725784e33a2ebf36a1.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: alertmanager-to-github-0.2.0-ee8a681cb08d0becda79f9725784e33a2ebf36a1.tgz
dateCreated: '2025-12-04T02:11:30.019383Z'
digest: 5f689d26a3bb038b2b0d1a102d5f4333e0c705950382eaad43983c28510c1b67
home: https://github.com/giantswarm/alertmanager-to-github-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
