annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-1fa5bd369b4dd0b867765a245636150f516c3a20.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-1fa5bd369b4dd0b867765a245636150f516c3a20.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-1fa5bd369b4dd0b867765a245636150f516c3a20.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-1fa5bd369b4dd0b867765a245636150f516c3a20.tgz
dateCreated: '2025-11-06T07:27:33.234389Z'
digest: 9661bfdaab43d994c1ea160764c0bbe6d4720cfce7dd46ab3846c813803213a9
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
