annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-8f261bc1ffb16cb467402a41bbaae4d2251859db.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-8f261bc1ffb16cb467402a41bbaae4d2251859db.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-8f261bc1ffb16cb467402a41bbaae4d2251859db.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-8f261bc1ffb16cb467402a41bbaae4d2251859db.tgz
dateCreated: '2025-11-03T10:32:23.742292Z'
digest: 201fc7cf36b53fff5814ee0bc499ca25637435eeeba62c5e5362a282bd259082
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
