annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.1-ef0c732242096e6b4eb53051a3a5d322a5d7bb29.tgz
dateCreated: '2026-01-07T18:16:30.970281Z'
digest: 0252f3bf4f98b42255f5a0b686386f622cb33ce33dffbc57f8b573190b8bd489
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
