annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.1-30b367ac7e81dee58471f2f74c12f8c6c38fc612.tgz
dateCreated: '2026-01-06T13:56:44.146818Z'
digest: 9b845974af3d9b72da33b972c247448a2e554988ba97166d9b29e00cfbbf135d
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
