annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.1-8a9821cec4e95735d6190a9871776eddb1a2ed23.tgz
dateCreated: '2026-01-05T15:51:04.961100Z'
digest: f1436a24b46f35f9a3230c24910c46ff3c5f7c558f9527e3c5b500b6c9a48511
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
