annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-24a3c1b8f0d440b2b5ec03b5fc7905993eb75667.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-24a3c1b8f0d440b2b5ec03b5fc7905993eb75667.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-24a3c1b8f0d440b2b5ec03b5fc7905993eb75667.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-24a3c1b8f0d440b2b5ec03b5fc7905993eb75667.tgz
dateCreated: '2025-11-26T06:11:48.110218Z'
digest: 735f529ec924590cf96a4d65b2f13654d321387ce4301bc6fc4365e75933fad4
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
