annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-4ad20fc0db93d3ed12102900b0ecc1b7e2da0853.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-4ad20fc0db93d3ed12102900b0ecc1b7e2da0853.tgz-meta/README.md
  application.giantswarm.io/team: planeteers
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-4ad20fc0db93d3ed12102900b0ecc1b7e2da0853.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.17-4ad20fc0db93d3ed12102900b0ecc1b7e2da0853.tgz
dateCreated: '2025-12-04T04:08:18.642226Z'
digest: 9e7e357075b8c27085d90678ddadd95616e616a15487710a68c5bb9c359735f5
home: https://github.com/giantswarm/mcp-prometheus
icon: https://github.com/prometheus/prometheus/raw/main/documentation/images/prometheus-logo.svg
