annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-57874951ed68080387175c92029773a379448c8e.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-57874951ed68080387175c92029773a379448c8e.tgz-meta/README.md
  application.giantswarm.io/team: planeteers
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-57874951ed68080387175c92029773a379448c8e.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.17-57874951ed68080387175c92029773a379448c8e.tgz
dateCreated: '2025-11-02T15:31:15.794109Z'
digest: 0580ef64370c08962b3c2e057f33085c1681f373afe6e64a33675f2532cf9931
home: https://github.com/giantswarm/mcp-prometheus
icon: https://github.com/prometheus/prometheus/raw/main/documentation/images/prometheus-logo.svg
