annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.0-8aeff1e766fd0b2f48680bc862ae20b838a11c35.tgz
dateCreated: '2025-12-29T13:25:47.313446Z'
digest: eafee3a406b32d2d8cd88a864c20f70f94ad0a19c2739a2756b1e63d79cf4b01
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
