annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-b59c71224cd69041b6d92e9a4d7a1aaddcf9eae9.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-b59c71224cd69041b6d92e9a4d7a1aaddcf9eae9.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-b59c71224cd69041b6d92e9a4d7a1aaddcf9eae9.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-b59c71224cd69041b6d92e9a4d7a1aaddcf9eae9.tgz
dateCreated: '2025-12-02T12:56:45.791712Z'
digest: 4b0a0742f237f88bef5a83968a4e797f6705eaa0eb21adb399d46123659daa1b
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
