annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/alertmanager-to-github-0.2.0-76a2daae8248d0798b0b1850d91e95229b96c9dd.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/alertmanager-to-github-0.2.0-76a2daae8248d0798b0b1850d91e95229b96c9dd.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/alertmanager-to-github-0.2.0-76a2daae8248d0798b0b1850d91e95229b96c9dd.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: alertmanager-to-github-0.2.0-76a2daae8248d0798b0b1850d91e95229b96c9dd.tgz
dateCreated: '2025-11-04T11:42:53.315678Z'
digest: b66fa2ba0e779eb1cf7956f31ddcb9a7bb6c103720333626cda634b62b5a9d9b
home: https://github.com/giantswarm/alertmanager-to-github-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
