annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-897dc99b624d7f3a779faa0f3cc7a7c5b5ff86be.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-897dc99b624d7f3a779faa0f3cc7a7c5b5ff86be.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-897dc99b624d7f3a779faa0f3cc7a7c5b5ff86be.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-897dc99b624d7f3a779faa0f3cc7a7c5b5ff86be.tgz
dateCreated: '2025-12-04T15:44:03.624795Z'
digest: 710af559819ffce1c91fad95325d352614e5ad0904d780715cb35c3b01dff2f1
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
