annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-2d3e7d69cae9b202b82370f8134cb2ba3715baf1.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-2d3e7d69cae9b202b82370f8134cb2ba3715baf1.tgz-meta/README.md
  application.giantswarm.io/team: planeteers
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-2d3e7d69cae9b202b82370f8134cb2ba3715baf1.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.17-2d3e7d69cae9b202b82370f8134cb2ba3715baf1.tgz
dateCreated: '2025-11-10T15:00:54.734289Z'
digest: f0c3d2fcd4e68ee3596a325a8d7967ac83ab95d7c863309e5dcfbc419563e751
home: https://github.com/giantswarm/mcp-prometheus
icon: https://github.com/prometheus/prometheus/raw/main/documentation/images/prometheus-logo.svg
