annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-19.0.0-fa1a22393a90b92602b7ab2a157ceb2f6c84a6d4.tgz
dateCreated: '2026-01-20T14:06:49.647539Z'
digest: 7c55ff5f20ad21ee428e387956189d50aeeb40e6dfdb50d70a4cfc01e296fe19
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
