annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-7bb29112ace1015959cc7c2e5586a90e83fbe547.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-7bb29112ace1015959cc7c2e5586a90e83fbe547.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-7bb29112ace1015959cc7c2e5586a90e83fbe547.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-7bb29112ace1015959cc7c2e5586a90e83fbe547.tgz
dateCreated: '2025-11-03T11:40:23.101312Z'
digest: b57e2d656ed342409dcdfe0b16e6b8a573daa6d286f49bdb2ec7b6aac4bde6b7
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
