annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-1754bfca4b017667f0c2ca217796f45adb09ea8e.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-1754bfca4b017667f0c2ca217796f45adb09ea8e.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-1754bfca4b017667f0c2ca217796f45adb09ea8e.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-1754bfca4b017667f0c2ca217796f45adb09ea8e.tgz
dateCreated: '2025-12-02T12:57:04.782330Z'
digest: 2b5666ae75cc4c0f4e3b888e5f163e6a38b726260b334e1183b22ceb18bacfc4
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
