annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-b554d9517fca2bb5e357628689b8776592bd848f.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-b554d9517fca2bb5e357628689b8776592bd848f.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-b554d9517fca2bb5e357628689b8776592bd848f.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-b554d9517fca2bb5e357628689b8776592bd848f.tgz
dateCreated: '2025-11-08T18:30:09.141697Z'
digest: a57262f27fac7fccf1fb8a00dcad2de19fe9c9df45530426c3d4d26dd65caee9
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
