annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-e530cf0953388e44ce2c516597764e9db4c51d33.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-e530cf0953388e44ce2c516597764e9db4c51d33.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-e530cf0953388e44ce2c516597764e9db4c51d33.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-e530cf0953388e44ce2c516597764e9db4c51d33.tgz
dateCreated: '2025-11-04T12:12:38.895370Z'
digest: 2df0fdb6e6cf2545f85cfd216e0990c1092fa08f5eb261b24a7bf4388e15b2e5
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
