annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-f1947c07794deb2f0b0c2572f662f7299a105ef6.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-f1947c07794deb2f0b0c2572f662f7299a105ef6.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-f1947c07794deb2f0b0c2572f662f7299a105ef6.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-f1947c07794deb2f0b0c2572f662f7299a105ef6.tgz
dateCreated: '2025-12-04T15:43:53.387919Z'
digest: a602d1b42e1aae643ceff68e59bc840231656e9cbe663aa0c138bfcd56aa1e25
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
