annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-26e74d80009c29f0ac98909ad294ee4533122572.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-26e74d80009c29f0ac98909ad294ee4533122572.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-26e74d80009c29f0ac98909ad294ee4533122572.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-26e74d80009c29f0ac98909ad294ee4533122572.tgz
dateCreated: '2025-12-05T17:40:07.558071Z'
digest: 795ea3d8a3278ac7870ad1ed4bbb10ff2dfad6ac7bffc3669c676b9efbee83be
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
