annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/prometheus-operator-crd-18.0.0-09b875f224e2573f0f38603c0d72d4d7059f2ebd.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/prometheus-operator-crd-18.0.0-09b875f224e2573f0f38603c0d72d4d7059f2ebd.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/prometheus-operator-crd-18.0.0-09b875f224e2573f0f38603c0d72d4d7059f2ebd.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-operator-crd-18.0.0-09b875f224e2573f0f38603c0d72d4d7059f2ebd.tgz
dateCreated: '2025-12-04T15:43:57.162971Z'
digest: bcf0a2854a616b016d131d6ec9d59e7fa9729b183cf29b0cfcc82fdaa4b9b3ca
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
