annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.1-0d970226444898112b023ab520352276251d5af7.tgz
dateCreated: '2026-01-20T14:06:57.645870Z'
digest: e75d6535c583ccde2803984eb884016c1b35a7e5110cefe7f73d6c669c859d2d
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
