annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-ee57b9c960a4c3c150a8d39bc2427f1cef710d5d.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-ee57b9c960a4c3c150a8d39bc2427f1cef710d5d.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-ee57b9c960a4c3c150a8d39bc2427f1cef710d5d.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-ee57b9c960a4c3c150a8d39bc2427f1cef710d5d.tgz
dateCreated: '2025-12-04T12:44:11.996754Z'
digest: a946ecd41c648a42b107f5fb75b39f806c317419263a9a63064b54cf8c813fc9
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
