annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-1ebfa4e720d4cbbdb0f9c25b477f811719d2a198.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-1ebfa4e720d4cbbdb0f9c25b477f811719d2a198.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-1ebfa4e720d4cbbdb0f9c25b477f811719d2a198.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-1ebfa4e720d4cbbdb0f9c25b477f811719d2a198.tgz
dateCreated: '2025-11-04T11:37:32.292253Z'
digest: cf1c457c5188e1ea39611a31d8d0f2e6070db06c7fce3c05e8f95fd51a7dcb49
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
