annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-b4154e2a2604d07355c902763259b35823f0b278.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-b4154e2a2604d07355c902763259b35823f0b278.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-b4154e2a2604d07355c902763259b35823f0b278.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-b4154e2a2604d07355c902763259b35823f0b278.tgz
dateCreated: '2025-12-02T12:55:42.335195Z'
digest: 5a3579271bbd13b4656bbb26cd3787b7293d9f70e3421e1e5cfc9c2c1c14f983
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
