annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-778203f65601b90e7fc038c89859192b350070ad.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-778203f65601b90e7fc038c89859192b350070ad.tgz-meta/README.md
  application.giantswarm.io/team: planeteers
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-778203f65601b90e7fc038c89859192b350070ad.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.17-778203f65601b90e7fc038c89859192b350070ad.tgz
dateCreated: '2025-12-29T04:48:05.190180Z'
digest: 8f334533ff8d832f9657ce6e9efa836a4d8cafa4b4470a449abcc51e6be26e41
home: https://github.com/giantswarm/mcp-prometheus
icon: https://github.com/prometheus/prometheus/raw/main/documentation/images/prometheus-logo.svg
