annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-d089ed1f0ddee89705904c8edaac6176a7a4de0f.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-d089ed1f0ddee89705904c8edaac6176a7a4de0f.tgz-meta/README.md
  application.giantswarm.io/team: planeteers
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/mcp-prometheus-0.0.17-d089ed1f0ddee89705904c8edaac6176a7a4de0f.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.17-d089ed1f0ddee89705904c8edaac6176a7a4de0f.tgz
dateCreated: '2025-11-10T00:31:06.786185Z'
digest: 66e8f232ae8d278f7d90eacbb60f363f93730d14e07f952ce0a5b7bd178b4f53
home: https://github.com/giantswarm/mcp-prometheus
icon: https://github.com/prometheus/prometheus/raw/main/documentation/images/prometheus-logo.svg
