annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-8d74f0e4df2376d1d76dfe37b4cfa93c664325ab.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-8d74f0e4df2376d1d76dfe37b4cfa93c664325ab.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-8d74f0e4df2376d1d76dfe37b4cfa93c664325ab.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-8d74f0e4df2376d1d76dfe37b4cfa93c664325ab.tgz
dateCreated: '2025-11-25T21:40:29.458732Z'
digest: 88b397e8d7e44c5e46d8a0316900569e9ea5f9d6c4ac782c6678fc27a8cc35fd
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
