annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-18.0.0-6db78469c9439c47e2a9ab0480a0374b4acbfa96.tgz
dateCreated: '2025-12-10T12:35:47.552795Z'
digest: a29fd77b76346a1f54755c0184081d26c40e1668ab0182b4ab5f002c5a346326
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
