annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-7ef04b974438bc8ffda2bdaaf7f6c741be7787a3.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-7ef04b974438bc8ffda2bdaaf7f6c741be7787a3.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-7ef04b974438bc8ffda2bdaaf7f6c741be7787a3.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-7ef04b974438bc8ffda2bdaaf7f6c741be7787a3.tgz
dateCreated: '2025-11-07T16:36:57.848991Z'
digest: bdf38f1ba1b8b0390b6dbcdf5d9ddbe4ef02a5ec92f79b2f3c7e503fd7be867c
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
