annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-96d1954f543d501c087c4f69fd5f53587ad74759.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-96d1954f543d501c087c4f69fd5f53587ad74759.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-96d1954f543d501c087c4f69fd5f53587ad74759.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-96d1954f543d501c087c4f69fd5f53587ad74759.tgz
dateCreated: '2025-12-07T21:58:09.917785Z'
digest: 6239f67b9164eb0604860cc127f748de00e0088bcf0a727fa0ede4f96b814039
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
