annotations:
  application.giantswarm.io/team: planeteers
chartApiVersion: v2
chartFile: mcp-prometheus-0.0.17-6f4f81d398987b484b0a8a30459f962f07d0f72e.tgz
dateCreated: '2026-01-20T13:48:11.249879Z'
digest: e87b1e407ec2ddb18af4e0bacb2d73f2bc871ab84f28e39ec5379a25025fd9ab
home: https://github.com/giantswarm/mcp-prometheus
icon: https://github.com/prometheus/prometheus/raw/main/documentation/images/prometheus-logo.svg
