annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-operator-crd-18.0.0-097a77e5a054250d1f9c339c0f2192152d79ed81.tgz
dateCreated: '2025-12-10T02:51:16.781038Z'
digest: 5a3cb84f5c38c89ae945db7f08f616049b36edfe18ee5ec446cc3ae3cf9bcadd
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
