annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-24f3cdcfdc16adbaf0af7565ddc586a187e14535.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-24f3cdcfdc16adbaf0af7565ddc586a187e14535.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-24f3cdcfdc16adbaf0af7565ddc586a187e14535.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-24f3cdcfdc16adbaf0af7565ddc586a187e14535.tgz
dateCreated: '2025-11-11T17:42:29.977219Z'
digest: 93f6e451af3e09d80aebe272c5ee33e474bfe83a2b1d0d3e7b1fd6a6f4a55e2b
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
