annotations:
  application.giantswarm.io/team: atlas
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: alertmanager-to-github-0.2.0-4e911c927b44c9b02df9dee77bccf8dc6f222eb2.tgz
dateCreated: '2026-01-05T16:06:23.096634Z'
digest: 9f35ebda6d3aea44a3967ff6748459a1821ee6f886e8bb4680e5ad43322afe8d
home: https://github.com/giantswarm/alertmanager-to-github-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
