annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-17f88bd92938c761b62ca2e9b76bfc0600f2dd02.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-17f88bd92938c761b62ca2e9b76bfc0600f2dd02.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-17f88bd92938c761b62ca2e9b76bfc0600f2dd02.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-17f88bd92938c761b62ca2e9b76bfc0600f2dd02.tgz
dateCreated: '2025-12-02T17:42:36.962668Z'
digest: b2b0ea32e9a987665235b16be5e040911a1b1a129e7a3aa0f1aba1510d46e480
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
