annotations:
  application.giantswarm.io/team: atlas
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: alertmanager-to-github-0.2.0-378676492c62f5ba3e0b61202e14b77965dd53d4.tgz
dateCreated: '2026-01-20T13:47:03.232689Z'
digest: 197cdb225592a4c4845a321f4002e7c390331be13953c912104f434d6acaac30
home: https://github.com/giantswarm/alertmanager-to-github-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
