annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: kube-prometheus-stack-19.0.1-a370c9ad69a4f3528cac9ee0633e6f841e659955.tgz
dateCreated: '2026-01-20T10:15:33.473309Z'
digest: 9f3cfb420147fb73886ae3cee04d653e0ce1df7527873ec829bc49397777d611
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
