annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-d2dfd2788d35c9f360e985dc5bd32c036b9efe8c.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-d2dfd2788d35c9f360e985dc5bd32c036b9efe8c.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/giantswarm-test-catalog/kube-prometheus-stack-18.1.0-d2dfd2788d35c9f360e985dc5bd32c036b9efe8c.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0-d2dfd2788d35c9f360e985dc5bd32c036b9efe8c.tgz
dateCreated: '2025-11-21T15:37:24.617594Z'
digest: ac867c133556b12dcba2b5ed9e597421483541e9446012795bf3a29ad8e471fc
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
